
#pragma once

#include <QObject>
#include <QDialog>
#include <QString>
#include <QMap>
#include <QLineEdit>
#include <QMessageBox>

#include "../../utils.h"
#include "../../bridge.h"
#include "../../wrapper_classes.h"
#include "ui_workspace_save.h"


/* NOTE FOR THE DEVELOPERS:
 * All Menu Dialog classes MUST
 * 1. inherit from MixinSettings,
 * 2. use the extractAndVerify() method to extract input data from fields,
 * 3. call the Q_OBJECT macro at the beginning of the class to allow slots and signals (see documentation of Qt),
 * 4. have a private pointer *ui to the associated class generated by the Qt Designer.
 */
class SaveWorkspaceDialog : public MixinSettings
{
    Q_OBJECT

private:
    Ui::save_workspace* ui;

public:
    SaveWorkspaceDialog(QSettings& settings, QWidget* parent = nullptr, Qt::WindowFlags f = Qt::WindowFlags());
    ~SaveWorkspaceDialog();

private:
    void save_component(const QString& type, const bool accept = true);

public slots:
    void save_comments();
    void save_equations();
    void save_identities();
    void save_lists();
    void save_scalars();
    void save_tables();
    void save_variables();
	void save();
};
