
#pragma once

#include <QObject>
#include <QDialog>
#include <QString>
#include <QSettings>
#include <QMap>
#include <QMessageBox>

#include <string>

#include "../../utils.h"
#include "../../bridge.h"
#include "../../wrapper_classes.h"
#include "ui_workspace_load.h"


/* NOTE FOR THE DEVELOPERS:
 * All Menu Dialog classes MUST 
 * 1. inherit from MixinSettings,
 * 2. use the extractAndVerify() method to extract input data from fields,
 * 3. call the Q_OBJECT macro at the beginning of the class to allow slots and signals (see documentation of Qt),
 * 4. have a private pointer *ui to the associated class generated by the Qt Designer.
 */
class LoadWorkspaceDialog : public MixinSettings
{
    Q_OBJECT

private:
    Ui::load_workspace* ui;

public:
    LoadWorkspaceDialog(QSettings& settings, QWidget* parent = nullptr, Qt::WindowFlags f = Qt::WindowFlags());
    ~LoadWorkspaceDialog();

private:
    void load_component(const QString& type, const bool accept = true);

public slots:
    void load_comments();
    void load_equations();
    void load_identities();
    void load_lists();
    void load_scalars();
    void load_tables();
    void load_variables();
	void load();
};
