# .github/release.yml

changelog:
  categories:
    - title: New Features 
      labels:
        - feature
    - title: Improvements 
      labels:
        - enhancement
    - title: Fixed Bugs 
      labels:
        - bug
    - title: Miscellaneous 
      labels:
        - "*"
      exclude:
        labels:
          - skip_for_changelog
