# DIRS : SCR, IODE, TEECHART
# --------------------------

IODEDIR     = $(MAKEDIR)\..\..
IODEINCDIR  = $(IODEDIR)\api
IODEAPIDIR  = $(IODEDIR)\api
IODEDOSDIR  = $(IODEDIR)\dos

SCRDIR      = $(IODEDIR)\scr4
SCRINCDIR   = $(SCRDIR)
SCRLIBDIR   = $(SCRDIR)\$(SYSVERS)
SCREXEDIR   = $(SCRDIR)\$(SYSVERS)

TEECHART    = c:\usr\TeeChart
