"""
Stub module for iode_cython (Cython-compiled C++ extension).

This file is AUTO-GENERATED from pyiode/iode/iode_cython.pyi.
It contains all classes, functions, and type annotations from the .pyi file.

On ReadTheDocs (Ubuntu), this stub is imported instead of the real module
(which is only available on Windows).

DO NOT EDIT THIS FILE MANUALLY - it will be regenerated from .pyi!
"""

import enum
import numpy as np
from pathlib import Path
from typing import Any

ESTIMATION_EPS: float = None
ESTIMATION_MAXIT: int = None
IODE_DEFAULT_DATABASE_FILENAME: str = None
NA: float = None
NAN_REP: str = None
allowed_keys: set = None
la: None = None

class AdjustmentMethod(enum.IntEnum):
    ERROR_CORRECTION = enum.auto()
    PARTIAL = enum.auto()

class BinaryOperation(enum.IntEnum):
    OP_ADD = enum.auto()
    OP_DIV = enum.auto()
    OP_MUL = enum.auto()
    OP_POW = enum.auto()
    OP_SUB = enum.auto()

class Comments:
    def convert_file(self, *args, **kwargs) -> Any:
        pass
    def __init__(self, *args, **kwargs):
        pass

    def copy_from(self, input_files, names):
        pass

    def initialize_subset(self, pattern, copy):
        pass

    def merge(self, other, overwrite):
        pass

    def __hash__(self):
        pass

    def __reduce__(self):
        pass


class ComputedTable:
    def __init__(self, *args, **kwargs):
        pass

    def cell_value_to_str(self, row, column):
        pass

    def get_columns(self):
        pass

    def get_files(self):
        pass

    def get_graph_axis(self):
        pass

    def get_gridx(self):
        pass

    def get_gridy(self):
        pass

    def get_lines(self):
        pass

    def get_nb_columns(self):
        pass

    def get_nb_decimals(self):
        pass

    def get_nb_files(self):
        pass

    def get_nb_lines(self):
        pass

    def get_nb_operations_between_files(self):
        pass

    def get_nb_periods(self):
        pass

    def get_sample(self):
        pass

    def get_text_alignment(self):
        pass

    def get_title(self):
        pass

    def get_ymax(self):
        pass

    def get_ymin(self):
        pass

    def is_editable(self, row, column):
        pass

    def plotting_series_name(self, row, op_files):
        pass

    def plotting_series_values(self, row, op_files):
        pass

    def print_to_file(self, destination_file, format):
        pass

    def set_nb_decimals(self, value):
        pass

    def to_numpy(self):
        pass

    def __reduce__(self):
        pass


class CythonCorrelationMatrix:
    def __init__(self, *args, **kwargs):
        pass

    def get_names(self):
        pass

    def get_shape(self):
        pass

    def is_undefined(self):
        pass

    def name(self, index):
        pass

    def __getitem__(self, index):
        pass

    def __len__(self):
        pass

    def __reduce__(self):
        pass


class CythonEditAndEstimateEquations:
    def __init__(self, *args, **kwargs):
        pass

    def estimate(self, maxit, epsilon):
        pass

    def get_block(self):
        pass

    def get_correlation_matrix(self):
        pass

    def get_current_equation(self):
        pass

    def get_equations_db(self):
        pass

    def get_equations_list(self):
        pass

    def get_fitted_values(self, name):
        pass

    def get_instruments(self):
        pass

    def get_is_done(self):
        pass

    def get_method(self):
        pass

    def get_next_equation(self):
        pass

    def get_observed_values(self, name):
        pass

    def get_residual_values(self, name):
        pass

    def get_sample(self):
        pass

    def get_scalars_db(self):
        pass

    def save(self, from_period, to_period):
        pass

    def set_block(self, block, current_eq_name):
        pass

    def set_instruments(self, value):
        pass

    def set_method(self, value):
        pass

    def set_sample(self, from_period, to_period):
        pass

    def update_current_equation(self, lec, comment):
        pass

    def update_scalars(self):
        pass

    def __reduce__(self):
        pass


class CythonIodeDatabase:
    def __init__(self, *args, **kwargs):
        pass

    def clear(self):
        pass

    def compare(self, args, i_iode_type):
        pass

    def contains(self, item):
        pass

    def get_description(self):
        pass

    def get_filename(self):
        pass

    def get_iode_type(self):
        pass

    def get_is_detached(self):
        pass

    def get_is_global_workspace(self):
        pass

    def get_name(self, pos):
        pass

    def get_names(self, pattern, filepath):
        pass

    def get_names_from_pattern(self, list_name, pattern, xdim, ydim):
        pass

    def index(self, name):
        pass

    def merge_from(self, input_file):
        pass

    def print_to_file(self, filepath, names, format):
        pass

    def property_names(self):
        pass

    def remove(self, names):
        pass

    def remove_objects(self, names):
        pass

    def rename(self, old_name, new_name, overwrite):
        pass

    def save(self, filepath, compress):
        pass

    def search(self, pattern, word, case_sensitive, in_name, in_formula, in_text, list_result):
        pass

    def set_description(self, value):
        pass

    def set_filename(self, value):
        pass

    def size(self):
        pass

    def __reduce__(self):
        pass


class CythonSimulation:
    def __init__(self, *args, **kwargs):
        pass

    def get_convergence_threshold(self):
        pass

    def get_debug(self):
        pass

    def get_debug_newton(self):
        pass

    def get_initialization_method(self):
        pass

    def get_initialization_method_long(self):
        pass

    def get_max_nb_iterations(self):
        pass

    def get_max_nb_iterations_newton(self):
        pass

    def get_nb_iterations(self, period):
        pass

    def get_nb_passes(self):
        pass

    def get_norm(self, period):
        pass

    def get_relax(self):
        pass

    def get_sort_algorithm(self):
        pass

    def get_sort_algorithm_long(self):
        pass

    def model_calculate_SCC(self, nb_iterations, pre_name, inter_name, post_name, list_eqs):
        pass

    def model_compile(self, list_eqs):
        pass

    def model_exchange(self, list_exo):
        pass

    def model_simulate(self, from_period, to_period, list_eqs):
        pass

    def model_simulate_SCC(self, from_period, to_period, pre_name, inter_name, post_name):
        pass

    def reset(self):
        pass

    def save_nb_iterations(self, var_name):
        pass

    def save_norms(self, var_name):
        pass

    def set_convergence_threshold(self, value):
        pass

    def set_debug(self, value):
        pass

    def set_debug_newton(self, value):
        pass

    def set_initialization_method(self, value):
        pass

    def set_max_nb_iterations(self, value):
        pass

    def set_max_nb_iterations_newton(self, value):
        pass

    def set_nb_passes(self, value):
        pass

    def set_relax(self, value):
        pass

    def set_sort_algorithm(self, value):
        pass

    def __reduce__(self):
        pass


class EqMethod(enum.IntEnum):
    GLS = enum.auto()
    INSTRUMENTAL = enum.auto()
    LSQ = enum.auto()
    MAX_LIKELIHOOD = enum.auto()
    ZELLNER = enum.auto()

class EqTest(enum.IntEnum):
    CORR = enum.auto()
    DW = enum.auto()
    FSTAT = enum.auto()
    LOGLIK = enum.auto()
    MEANY = enum.auto()
    R2 = enum.auto()
    R2ADJ = enum.auto()
    SSRES = enum.auto()
    STDERR = enum.auto()
    STDERRP = enum.auto()
    STDEV = enum.auto()

class Equation:
    def __init__(self, *args, **kwargs):
        pass

    def equal(self, other):
        pass

    def estimate(self, from_period, to_period, maxit, epsilon):
        pass

    def estimate_step_wise(self, from_period, to_period, lec_condition, test):
        pass

    def get_block(self):
        pass

    def get_coefficients(self):
        pass

    def get_comment(self):
        pass

    def get_endogenous(self):
        pass

    def get_formated_date(self, format):
        pass

    def get_instruments(self):
        pass

    def get_lec(self):
        pass

    def get_method(self):
        pass

    def get_sample(self):
        pass

    def get_tests(self):
        pass

    def get_variables(self):
        pass

    def reset_tests(self):
        pass

    def set_block(self, value):
        pass

    def set_comment(self, value):
        pass

    def set_instruments(self, value):
        pass

    def set_lec(self, value):
        pass

    def set_method(self, value):
        pass

    def set_sample(self, from_period, to_period):
        pass

    def split_equation(self):
        pass

    def __hash__(self):
        pass

    def __reduce__(self):
        pass


class Equations:
    def __init__(self, *args, **kwargs):
        pass

    def copy_from(self, input_files, names):
        pass

    def estimate(self, from_period, to_period, list_eqs, maxit, epsilon):
        pass

    def get_lec(self, name):
        pass

    def get_print_equations_as(self):
        pass

    def get_print_equations_lec_as(self):
        pass

    def initialize_subset(self, pattern, copy):
        pass

    def merge(self, other, overwrite):
        pass

    def set_print_equations_as(self, value):
        pass

    def set_print_equations_lec_as(self, value):
        pass

    def __hash__(self):
        pass

    def __reduce__(self):
        pass


class ExportFormats(enum.IntEnum):
    CSV = enum.auto()
    DIF = enum.auto()
    RCSV = enum.auto()
    TSP = enum.auto()
    WKS = enum.auto()

class HighToLowType(enum.IntEnum):
    LAST = enum.auto()
    MEAN = enum.auto()
    SUM = enum.auto()

class Identities:
    def __init__(self, *args, **kwargs):
        pass

    def copy_from(self, input_files, names):
        pass

    def execute(self, identities, from_period, to_period, var_files, scalar_files, trace):
        pass

    def initialize_subset(self, pattern, copy):
        pass

    def merge(self, other, overwrite):
        pass

    def __hash__(self):
        pass

    def __reduce__(self):
        pass


class Identity:
    def __init__(self, *args, **kwargs):
        pass

    def equal(self, other):
        pass

    def get_coefficients(self):
        pass

    def get_lec(self):
        pass

    def get_variables(self):
        pass

    def set_lec(self, value):
        pass

    def __reduce__(self):
        pass


class ImportFormats(enum.IntEnum):
    ASCII = enum.auto()
    BISTEL = enum.auto()
    DIF = enum.auto()
    GEM = enum.auto()
    NIS = enum.auto()
    PRN = enum.auto()
    ROT_ASCII = enum.auto()
    TXT = enum.auto()

class IodeFileType(enum.IntEnum):
    DIRECTORY = enum.auto()
    FILE_A2M = enum.auto()
    FILE_AAS = enum.auto()
    FILE_AGL = enum.auto()
    FILE_ANY = enum.auto()
    FILE_COMMENTS = enum.auto()
    FILE_CSV = enum.auto()
    FILE_DIF = enum.auto()
    FILE_EQUATIONS = enum.auto()
    FILE_HTML = enum.auto()
    FILE_IDENTITIES = enum.auto()
    FILE_LISTS = enum.auto()
    FILE_LOG = enum.auto()
    FILE_MIF = enum.auto()
    FILE_PRF = enum.auto()
    FILE_PS = enum.auto()
    FILE_REF = enum.auto()
    FILE_REP = enum.auto()
    FILE_RTF = enum.auto()
    FILE_SCALARS = enum.auto()
    FILE_SETTINGS = enum.auto()
    FILE_TABLES = enum.auto()
    FILE_TXT = enum.auto()
    FILE_VARIABLES = enum.auto()

class IodeType(enum.IntEnum):
    COMMENTS = enum.auto()
    EQUATIONS = enum.auto()
    IDENTITIES = enum.auto()
    LISTS = enum.auto()
    SCALARS = enum.auto()
    TABLES = enum.auto()
    VARIABLES = enum.auto()

class Lists:
    def __init__(self, *args, **kwargs):
        pass

    def copy_from(self, input_files, names):
        pass

    def initialize_subset(self, pattern, copy):
        pass

    def merge(self, other, overwrite):
        pass

    def __hash__(self):
        pass

    def __reduce__(self):
        pass


class LowToHighMethod(enum.StrEnum):
    CUBIC_SPLINES = enum.auto()
    LINEAR = enum.auto()
    STEP = enum.auto()

class LowToHighType(enum.IntEnum):
    FLOW = enum.auto()
    STOCK = enum.auto()

class Period:
    def __init__(self, *args, **kwargs):
        pass

    def difference(self, other):
        pass

    def get_nb_periods_per_year(self):
        pass

    def get_periodicity(self):
        pass

    def get_step(self):
        pass

    def get_year(self):
        pass

    def shift(self, nb_periods):
        pass

    def __eq__(self, other):
        pass

    def __float__(self):
        pass

    def __ge__(self, other):
        pass

    def __gt__(self, other):
        pass

    def __le__(self, other):
        pass

    def __lt__(self, other):
        pass

    def __ne__(self, other):
        pass

    def __reduce__(self):
        pass


class Sample:
    def __init__(self, *args, **kwargs):
        pass

    def get_end(self):
        pass

    def get_nb_periods(self):
        pass

    def get_period_list(self, astype):
        pass

    def get_start(self):
        pass

    def index(self, period):
        pass

    def intersection(self, other_sample):
        pass

    def is_undefined(self):
        pass

    def __eq__(self, other):
        pass

    def __ge__(self, other):
        pass

    def __gt__(self, other):
        pass

    def __le__(self, other):
        pass

    def __len__(self):
        pass

    def __lt__(self, other):
        pass

    def __ne__(self, other):
        pass

    def __reduce__(self):
        pass


class Scalar:
    def __init__(self, *args, **kwargs):
        pass

    def equal(self, other):
        pass

    def get_relax(self):
        pass

    def get_std(self):
        pass

    def get_value(self):
        pass

    def set_relax(self, value):
        pass

    def set_value(self, value):
        pass

    def __hash__(self):
        pass

    def __reduce__(self):
        pass


class Scalars:
    def __init__(self, *args, **kwargs):
        pass

    def copy_from(self, input_files, names):
        pass

    def initialize_subset(self, pattern, copy):
        pass

    def merge(self, other, overwrite):
        pass

    def __hash__(self):
        pass

    def __reduce__(self):
        pass


class SimulationInitialization(enum.IntEnum):
    ASIS = enum.auto()
    EXTRA = enum.auto()
    EXTRA_A = enum.auto()
    EXTRA_NA = enum.auto()
    TM1 = enum.auto()
    TM1_A = enum.auto()
    TM1_NA = enum.auto()

class SimulationSort(enum.IntEnum):
    BOTH = enum.auto()
    CONNEX = enum.auto()
    NONE = enum.auto()

class Table:
    def __init__(self, *args, **kwargs):
        pass

    def compute(self, generalized_sample, nb_decimals):
        pass

    def get_coefficients(self):
        pass

    def get_divider(self):
        pass

    def get_graph_axis(self):
        pass

    def get_gridx(self):
        pass

    def get_gridy(self):
        pass

    def get_language(self):
        pass

    def get_nb_columns(self):
        pass

    def get_nb_lines(self):
        pass

    def get_text_alignment(self):
        pass

    def get_title(self):
        pass

    def get_variables(self):
        pass

    def index(self, key):
        pass

    def insert(self, row, value):
        pass

    def set_divider(self, value):
        pass

    def set_graph_axis(self, value):
        pass

    def set_gridx(self, value):
        pass

    def set_gridy(self, value):
        pass

    def set_language(self, value):
        pass

    def set_text_alignment(self, value):
        pass

    def set_title(self, value):
        pass

    def __hash__(self):
        pass

    def __reduce__(self):
        pass


class TableCell:
    def __init__(self, *args, **kwargs):
        pass

    def get_align(self):
        pass

    def get_bold(self):
        pass

    def get_cell_type(self):
        pass

    def get_coefficients(self):
        pass

    def get_italic(self):
        pass

    def get_underline(self):
        pass

    def get_variables(self):
        pass

    def set_align(self, value):
        pass

    def set_bold(self, value):
        pass

    def set_italic(self, value):
        pass

    def set_underline(self, value):
        pass

    def __reduce__(self):
        pass


class TableCellAlign(enum.IntEnum):
    CENTER = enum.auto()
    DECIMAL = enum.auto()
    LEFT = enum.auto()
    RIGHT = enum.auto()

class TableCellFont(enum.IntEnum):
    BOLD = enum.auto()
    ITALIC = enum.auto()
    NORMAL = enum.auto()
    UNDERLINE = enum.auto()

class TableCellType(enum.IntEnum):
    LEC = enum.auto()
    STRING = enum.auto()

class TableGraphAxis(enum.IntEnum):
    LOG = enum.auto()
    PERCENT = enum.auto()
    SEMILOG = enum.auto()
    VALUES = enum.auto()

class TableGraphGrid(enum.IntEnum):
    MAJOR = enum.auto()
    MINOR = enum.auto()
    NONE = enum.auto()

class TableGraphType(enum.IntEnum):
    BAR = enum.auto()
    LINE = enum.auto()
    SCATTER = enum.auto()

class TableLang(enum.IntEnum):
    DUTCH = enum.auto()
    ENGLISH = enum.auto()
    FRENCH = enum.auto()

class TableLine:
    def __init__(self, *args, **kwargs):
        pass

    def get_axis_left(self):
        pass

    def get_graph_type(self):
        pass

    def get_type(self):
        pass

    def set_axis_left(self, value):
        pass

    def set_graph_type(self, value):
        pass

    def size(self):
        pass

    def __reduce__(self):
        pass


class TableLineType(enum.IntEnum):
    CELL = enum.auto()
    DATE = enum.auto()
    FILES = enum.auto()
    MODE = enum.auto()
    SEP = enum.auto()
    TITLE = enum.auto()

class TableTextAlign(enum.IntEnum):
    CENTER = enum.auto()
    LEFT = enum.auto()
    RIGHT = enum.auto()

class Tables:
    def __init__(self, *args, **kwargs):
        pass

    def copy_from(self, input_files, names):
        pass

    def cpp_tables_print_to_file(self, filepath, names, format, generalized_sample, nb_decimals):
        pass

    def get_print_tables_as(self):
        pass

    def get_title(self, name):
        pass

    def initialize_subset(self, pattern, copy):
        pass

    def merge(self, other, overwrite):
        pass

    def set_print_tables_as(self, value):
        pass

    def __hash__(self):
        pass

    def __reduce__(self):
        pass


class Variables:
    def convert_file(self, *args, **kwargs) -> Any:
        pass
    def export_as_file(self, *args, **kwargs) -> Any:
        pass
    def __init__(self, *args, **kwargs):
        pass

    def binary_op_numpy(self, data, op, names, nb_periods, copy_self):
        pass

    def binary_op_scalar(self, other, op, copy_self):
        pass

    def binary_op_variables(self, cython_other, op, names, copy_self):
        pass

    def copy_from(self, input_files, from_period, to_period, names):
        pass

    def execute_RAS(self, pattern, xdim, ydim, ref_period, sum_period, max_nb_iterations, epsilon):
        pass

    def extrapolate(self, method, from_period, to_period, variables_list):
        pass

    def finish_clear(self):
        pass

    def from_numpy(self, data, vars_names, new_vars, t_first_period, t_last_period):
        pass

    def get_first_period(self):
        pass

    def get_is_subset_over_periods(self):
        pass

    def get_last_period(self):
        pass

    def get_mode(self):
        pass

    def get_sample(self):
        pass

    def get_threshold(self):
        pass

    def high_to_low(self, type_of_series, filepath, var_list):
        pass

    def initialize_subset(self, pattern, copy, first_period, last_period):
        pass

    def low_to_high(self, type_of_series, method, filepath, var_list):
        pass

    def merge(self, other, overwrite):
        pass

    def periods_subset(self, from_period, to_period, as_float):
        pass

    def seasonal_adjustment(self, input_file, eps_test, series):
        pass

    def set_mode(self, value):
        pass

    def set_sample(self, from_period, to_period):
        pass

    def set_threshold(self, value):
        pass

    def to_numpy(self):
        pass

    def trend_correction(self, input_file, lambda_, series, log):
        pass

    def __hash__(self):
        pass

    def __reduce__(self):
        pass


class VarsMode(enum.IntEnum):
    DIFF = enum.auto()
    GROWTH_RATE = enum.auto()
    LEVEL = enum.auto()
    Y0Y_DIFF = enum.auto()
    Y0Y_GROWTH_RATE = enum.auto()

class WriteFileExt(enum.IntEnum):
    A2M = enum.auto()
    CSV = enum.auto()
    DUMMY = enum.auto()
    GDI = enum.auto()
    HTML = enum.auto()
    MIF = enum.auto()
    RTF = enum.auto()

def __reduce_cython__(self):
    pass

def __setstate_cython__(self, __pyx_state):
    pass

def alloc_doc_loop():
    pass

def always_continue(value):
    pass

def backup_super_functions(*args, **kwargs):
    pass

def cython_build_command_functions_list(group, gui):
    pass

def cython_build_lec_functions_list():
    pass

def cython_build_report_functions_list():
    pass

def cython_define(name, macro):
    pass

def cython_dickey_fuller_test(lec, drift, trend, order):
    pass

def cython_dynamic_adjustment(method, eqs, c1, c2):
    pass

def cython_execute_command(command):
    pass

def cython_execute_lec(lec, period):
    pass

def cython_execute_report(filepath, parameters):
    pass

def cython_increment_time(n):
    pass

def cython_is_NA(value):
    pass

def cython_load_extra_files(extra_files):
    pass

def cython_macro(name):
    pass

def cython_macro_exists(name):
    pass

def cython_reset_extra_files():
    pass

def cython_set_time(period):
    pass

def cython_skip_message(value):
    pass

def cython_skip_msg_box(value):
    pass

def cython_skip_pause(value):
    pass

def cython_write(txt):
    pass

def cython_write_close():
    pass

def cython_write_code_block(level):
    pass

def cython_write_destination(filename, file_type):
    pass

def cython_write_enum(level):
    pass

def cython_write_flush():
    pass

def cython_write_page_footer(arg):
    pass

def cython_write_page_header(arg):
    pass

def cython_write_paragraph(level):
    pass

def cython_write_title(level):
    pass

def finish_cli():
    pass

def get_total_allocated_memory():
    pass

def initialize_cli():
    pass

def iode_confirm(message):
    pass

def iode_error(message):
    pass

def iode_information(message):
    pass

def iode_msg(message):
    pass

def iode_panic():
    pass

def iode_pause():
    pass

def iode_warning(message):
    pass

def register_super_function(name):
    def decorator(func):
        return func
    return decorator

def restore_super_functions(registry_funcs_backup):
    pass

def set_A2M_preferences(escape_char, cell_separator, define_char, command_char, append, preserve_spaces, preserve_linefeed, default_paragraph, graph_width, graph_height, graph_background_color, graph_background_brush, graph_box):
    pass

def set_HTML_preferences(font_size, font_family, table_font_family, font_incr, table_font_size, paragraph_numbers, table_border_width, table_use_color, generate_toc, body_tag, title):
    pass

def set_MIF_preferences(font_size, font_incr, font_family, table_font_family, table_font_size, table_use_color, table_first_col_width, table_other_col_width, table_split, table_width, table_outside_borders, table_horizontal_lines, table_vertical_lines, image_ref_in_text):
    pass

def set_RTF_preferences(font_size, font_incr, font_family, table_font_family, table_font_size, paragraph_numbers, table_use_color, table_first_col_width, table_other_col_width, table_width, table_outside_borders, table_horizontal_lines, table_vertical_lines, table_split_tables, prepare_for_hcw, compress_help, generate_toc, help_title, copyright):
    pass

def set_log_file_cli(log_file):
    pass

def set_printer_preferences(font_size, font_family, table_font_family, font_incr, table_font_size, paragraph_numbers, left_margin, right_margin, top_margin, bottom_margin, black_and_white, table_border_width, table_break, table_new_page, graph_new_page, table_shading, page_header, page_footer, ask_prompt):
    pass


def _get_file_types():
    return []  # Placeholder for the actual implementation
