# Composite Action
# See https://docs.github.com/en/actions/creating-actions/creating-a-composite-action 
# and https://stackoverflow.com/a/75279262 

name: test_api
description: 'Test the C and C++ API'
inputs:
  os-env:
    description: 'CMake build config'
    required: true
    default: 'windows'
  build-config:
    description: 'CMake build mode'
    required: true
    default: 'debug'
runs:
  using: 'composite'
  steps:
    - name: Build C/C++ Tests
      shell: bash
      run: cmake --build --verbose --preset ${{ inputs.os-env }}-${{ inputs.build-config }} --target test_all 
    - name: Run C API Tests
      shell: bash
      run: ctest --preset c-api-${{ inputs.os-env }}-${{ inputs.build-config }}
    - name: Run C++ API Tests
      shell: bash
      run: ctest --preset cpp-api-${{ inputs.os-env }}-${{ inputs.build-config }}
