
#pragma once

#include <QObject>
#include <QDialog>
#include <QString>
#include <QSettings>
#include <QMap>
#include <QMessageBox>

#include <string>

#include "../../utils.h"
#include "../../bridge.h"
#include "../../wrapper_classes.h"
#include "ui_print_A2M_file.h"


/* NOTE FOR THE DEVELOPERS:
 * All Menu Dialog classes MUST 
 * 1. inherit from MixinSettings,
 * 2. use the extractAndVerify() method to extract input data from fields,
 * 3. call the Q_OBJECT macro at the beginning of the class to allow slots and signals (see documentation of Qt),
 * 4. have a private pointer *ui to the associated class generated by the Qt Designer.
 */
 // TODO: implement the class below
class PrintA2MFileDialog : public MixinSettings
{
    Q_OBJECT

private:
    Ui::print_A2M_file* ui;

public:
    PrintA2MFileDialog(QSettings& settings, QWidget* parent = nullptr, Qt::WindowFlags f = Qt::WindowFlags());
    ~PrintA2MFileDialog();

public slots:
	void print();
	void setup();
};
