Version 7.0.8
=============

In development

New Features 
------------


Improvements 
------------


Fixed Bugs 
----------

- DOC: fixed wrong definition of the keyboard shortcut Alt + F[1-7] 
  in the PDF containing the list of keyboard shortcuts.

- PYTHON: fixed calling `execute_command(f"$WsLoadXxx filepath")` not 
  changing the workspace at the Python level (closes :issue:`1230`)

- GUI: fixed remembering previously executed commands in the Report Commands 
  console (closes :issue:`1228`)

fix #1228

Miscellaneous 
-------------

