Version 7.0.4
=============

In development

New Features 
------------


Improvements 
------------

- GUI: added the possibility to *save as* any tab using a "Save As" dialog 
  (closes :issue:`1076`)

Fixed Bugs 
----------

- GUI: fixed cells content not visible when editing an IODE table if Windows OS 
  is in dark mode (closes :issue:`1061`)
- GUI: fixed interface closing after catching an error thrown when executing an 
  IODE report (closes :issue:`1063`)
- GUI: fixed "File explorer" windows not updating when opening another project 
  (closes :issue:`1073`)
- GUI: fixed cascading tabs not working when extracting related IODE objects 
  (closes :issue:`1074`)

- NOTEPAD++: fixed color highlighting not working when opening IODE report files 
  (except for iode comments) (closes :issue:`521`)

Miscellaneous 
-------------

