Version 7.0.0-beta.7
====================

Released on 21/11/2024

New Features 
------------

  * (PYTHON) release of the new Python package *iode* (version 7.0.0) 

Improvements
------------

  * (GUI) Allowed users to open Iode files from an extern File Explorer using the option 'Open With' (#607)

Fixed Bugs
----------

  * (GUI) Fixed trying to overwrite a file (rename to as an existing file) just delete it (#546)
  * (GUI) Fixed shortcut CTRL + ALT + F2/F3 not showing equations/identities corresponding to 
          exogenous variables in an equation/identity (#603) 
  * (GUI) Fixed CTRL + F4 not working in tabs representing an Iode database (#609)
