Version 7.0.11
==============

In development

New Features 
------------


Improvements 
------------

- GUI: inside a text or report tab, the shortcuts `CTRL and +` and `CTRL and =` 
  increase the font size, while the shortcut `CTRL + -` decrease it 
  (closes :issue:`1236`) 


Fixed Bugs 
----------

- PYTHON: fixed crash when simulating a list of equations instead of the whole 
  equations workspace (closes :issue:`1319`)


Miscellaneous 
-------------

