Version 7.0.7
=============

In development

New Features 
------------


Improvements 
------------

- DOC: added section :ref:`API Reference <start_api_reports>` in the documentation.

- DOC: added new tutorial section for the `LEC language` in the documentation.

- DOC: added new tutorial section for the `IODE reports` in the documentation.

Fixed Bugs 
----------


Miscellaneous 
-------------

