Version 7.0.7
=============

In development

New Features 
------------


Improvements 
------------

- DOC: added section :ref:`API Reference <start_api_reports>` in the documentation.

- DOC: added new tutorial section for the `LEC language` in the documentation.

- DOC: added new tutorial section for the `IODE reports` in the documentation.

- GUI: pressing Tab when the auto-complete popup is visible will insert the first suggestion 
  (closes :issue:`1210`)

- GUI: added the *IODE Report API* link in the Help menu.

Fixed Bugs 
----------

- PYTHON: fixed crash when trying to run the :func:`execute_command` with an undefined macro 
  (closes :issue:`1200`)

- GUI: fixed shortcut `CTRL + K` to delete from the cursor to the end of the current line 
  (closes :issue:`1207`)

- GUI: fixed shortcut `CTRL + U` to delete the current line (closes :issue:`1208`)

- GUI: fixed shortcut `CTRL + L` to select the current line in a text or report editor 
  (closes :issue:`1209`)

Miscellaneous 
-------------

