Version 7.0.10
==============

In development

New Features 
------------


Improvements 
------------

- PYTHON: Speed up simulation process (especially the ordering of eqs process) after 
  a significant slowness introduced in version 7.0.5 (closes :issue:`1288`)

- PYTHON: Speed up merging and copying from file into IODE workspaces 
  (closes :issue:`1239`)

Fixed Bugs 
----------


Miscellaneous 
-------------

