Version7.0-beta.7
=================

In development

New Features 
------------


Improvements
------------

  * (GUI) Allowed users to open Iode files from an extern File Explorer using the option 'Open With' (#607)

Fixed Bugs
----------

  * (GUI) Fixed trying to overwrite a file (rename to as an existing file) just delete it (#546)
  * (GUI) Fixed shortcut CTRL + ALT + F2/F3 not showing equations/identities corresponding to 
          exogenous variables in an equation/identity (#603) 

Miscellaneous
-------------

