Version 7.0.3
=============

In development

New Features 
------------

- allowed the users to choose the displayed colors in the IODE report tabs 
  in the Graphical User Interface (GUI) (closes :issue:`1000`)

Improvements 
------------


Fixed Bugs 
----------

- forced to use dot as decimal separator in the 
  Graphical User Interface (GUI) for double values (closes :issue:`984`)
- fixed methods :meth:`Variables.from_frame` and :meth:`Variables.from_array` systematically 
  overriding the sample of the *variables* workspace (closes :issue:`998`)

Miscellaneous 
-------------

