Version 7.1.0
=============

In development

New Features 
------------


Improvements 
------------

  * PYTHON: added the boolean argument *compress* to the save() method of comments, ..., variables (same as $WsSaveCmp)
  * PYTHON: added the :meth:`Simulation.nb_iterations` method to get the number of iterations to converge 
    in the last simulation for a given period (same as @SimNIter) 

Fixed Bugs 
----------


Miscellaneous 
-------------

