
Miscellaneous Improvements
^^^^^^^^^^^^^^^^^^^^^^^^^^

* (GUI) Added `Open As Text` option to the context menu in the File Explorer (closes :issue:`268`).

* (GUI) Reload the values for the report parameters, language and nb decimals for each report tab when relaunching the GUI (closes :issue:`274`)

Fixes
^^^^^

* (GUI) fixed IODE database tabs not updated when calling $WsLoad<...> from an IODE report or using the IODE command line (closes :issue:`276`).

* (GUI) fixed IODE database tabs not updated when calling $WsClear<...> from an IODE report or using the IODE command line (closes :issue:`277`).

* (GUI) fixed double click on a IODE database file in the File Explorer not reloading it (closes :issue:`278`).
