# Composite Action
# See https://docs.github.com/en/actions/creating-actions/creating-a-composite-action 
# and https://stackoverflow.com/a/75279262 

name: test_big_files
description: 'Test the C and C++ API for big databases'
inputs:
  os-env:
    description: 'CMake build config'
    required: true
    default: 'windows'
  build-config:
    description: 'CMake build mode'
    required: true
    default: 'release'
runs:
  using: 'composite'
  steps:
    - name: Build C/C++ Tests for big databases
      shell: bash
      run: cmake --build --verbose --preset ${{ inputs.os-env }}-${{ inputs.build-config }} --target test_${{ inputs.build-config }}_big_files 
    - name: Run C/C++ API Tests for big databases
      shell: bash
      run: ctest --preset cpp-api-${{ inputs.os-env }}-${{ inputs.build-config }}-big-databases
