#!/usr/bin/env python3
"""
Generate a Python stub file (iode_cython.py) from iode_cython.pyi.

This script converts the existing .pyi type stub file into a pure Python module
that can be imported. This allows documentation to be built on ReadTheDocs (Ubuntu)
without needing the compiled iode_cython module.

How it works:
  1. Reads pyiode/iode/iode_cython.pyi (already exists in repository)
  2. Converts it to pyiode/rtd/iode_cython.py
  3. The .py file can be imported on any platform (no C++ extension needed)
  4. On ReadTheDocs, conf.py imports this stub instead of real module

Result:
    pyiode/rtd/iode_cython.py (importable on any platform)

Why use .pyi instead of introspection:
  - .pyi files are already maintained and up-to-date
  - They have proper type hints (better for documentation)
  - They're more reliable and maintainable
  - They're the standard format for Python type stubs
"""

import sys
from pathlib import Path


dummy_decorator = \
"""
def dummy_decorator(func):
    return func
"""


def convert_pyi_to_py(pyi_content: str) -> str:
    """Convert .pyi stub file to importable .py file."""
    lines = [
        '"""',
        'Stub module for iode_cython (Cython-compiled C++ extension).',
        '',
        'This file is AUTO-GENERATED from pyiode/iode/iode_cython.pyi.',
        'It contains all classes, functions, and type annotations from the .pyi file.',
        '',
        'On ReadTheDocs (Ubuntu), this stub is imported instead of the real module',
        '(which is only available on Windows).',
        '',
        'DO NOT EDIT THIS FILE MANUALLY - it will be regenerated from .pyi!',
        '"""',
        '',
        'import enum',
        'import numpy as np',
        'from pathlib import Path',
        'from typing import Any'
        '',
    ]

    enum_name = ""
    is_in_enum = False
    is_in_docstring = False
    for line in pyi_content.splitlines():
        # Skip import statements
        if 'import' in line:
            continue

        # Skip private members (starting with __)
        if line.strip().startswith('__'):
            continue

        # Skip docstrings (they are not needed in the stub)
        start_docstring = line.strip().startswith('"""') or line.strip().startswith("'''")
        end_docstring = line.strip().endswith('"""') or line.strip().endswith("'''")
        if start_docstring:
            is_in_docstring = True
            # If the docstring starts and ends on the same line, 
            # set is_in_docstring to False immediately
            if end_docstring:
                is_in_docstring = False 
            continue
        if end_docstring:
            is_in_docstring = False
            continue
        if is_in_docstring:
            continue

        # Parse enum classes
        if line.startswith('class') and ('enum.IntEnum' in line or 'enum.StrEnum' in line): 
            is_in_enum = True
            enum_name = line.split('class')[1].split('(')[0].strip()
            lines.append(line)
            continue

        if is_in_enum:
            # Found item of the current enum
            if f"ClassVar[{enum_name}]" in line:
                item = line.split(':')[0]
                lines.append(f"{item} = enum.auto()")
            # End of enum class
            elif line.strip() == "":
                is_in_enum = False
                enum_name = ""
                lines.append(line)
            # Skip other lines inside enum class
            else:
                pass
            continue

        # Parse classes declaration -> skip inheritance (it is a dummy file after all)
        if line.startswith('class'):
            if '(' in line:
                class_name = line.split('class')[1].split('(')[0].strip()
                lines.append(f"class {class_name}:")
            else:
                lines.append(line)
            continue

        # Parse @classmethod methods
        if 'ClassVar[method]' in line:
            method_name = line.split(':')[0].strip()
            lines.append(f"    def {method_name}(self, *args, **kwargs) -> Any:")
            lines.append(f"        pass")
            continue

        # Parse method or function signature (remove type annotations, keep only names and args)
        if line.strip().startswith('def'):
            indent = ' ' * (len(line) - len(line.lstrip()))
            func_name = line.split('def ')[1].split('(')[0].strip()
            args = line.split('(')[1].split(')')[0].strip()
            args = [arg.strip() for arg in args.split(',') if arg.strip() != '']
            # Remove type annotations from arguments (they are not needed in the stub)
            args = [arg.split(':')[0].strip() for arg in args]
            args = ', '.join(args)
            lines.append(f"{indent}def {func_name}({args}):")
            if func_name.startswith('register'):
                lines.append(f"{indent}    def decorator(func):")
                lines.append(f"{indent}        return func")
                lines.append(f"{indent}    return decorator")
            else:
                lines.append(f"{indent}    pass")
            lines.append("")
            continue

        # Parse empty lines (keep them)
        if line.strip() == "":
            lines.append(line)
            continue

        # Parse constants 
        # Set their value to None (they are not needed in the stub)
        is_indented = len(line) - len(line.lstrip())
        if not is_indented and not (line.startswith('class') or line.startswith('def')):
            lines.append(f"{line} = None")
            continue

        # Remove regex ": ClassVar[(\w*)] = ..." from each line
        if 'ClassVar' in line:
            line = line.split(': ClassVar')[0].rstrip()

        # Append the line as it
        lines.append(line)

    # Add function not in iode_cython.pyi but in the iode_cython.pyd file
    lines.append("")
    lines.append("def _get_file_types():")
    lines.append("    return []  # Placeholder for the actual implementation")
    lines.append("")  
    
    return '\n'.join(lines)


def main():
    # Get the directory structure
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    pyiode_dir = project_root / "pyiode"
    
    # Paths
    pyi_file = pyiode_dir / "iode" / "iode_cython.pyi"
    rtd_dir = pyiode_dir / "rtd"
    py_file = rtd_dir / "iode_cython.py"
    
    print("Generating Python stub file from iode_cython.pyi...")
    print(f"Input:  {pyi_file}")
    print(f"Output: {py_file}")
    
    # Check if .pyi file exists
    if not pyi_file.exists():
        print(f"X - .pyi file not found: {pyi_file}")
        print("  This file should exist in the repository.")
        return 1
    
    # Read the .pyi file
    try:
        with open(pyi_file, 'r', encoding='utf-8') as f:
            pyi_content = f.read()
        print(f"V - Read .pyi file ({pyi_file.stat().st_size / 1024:.1f} KB)")
    except Exception as e:
        print(f"X - Failed to read .pyi file: {e}")
        return 1
    
    # Create rtd directory
    rtd_dir.mkdir(parents=True, exist_ok=True)
    
    # Convert pyi to py
    py_content = convert_pyi_to_py(pyi_content)
    
    # Write the .py file
    try:
        with open(py_file, 'w', encoding='utf-8') as f:
            f.write(py_content)
        print(f"V - Generated stub file: {py_file}")
        print(f"- File size: {py_file.stat().st_size / 1024:.1f} KB")
    except Exception as e:
        print(f"X - Failed to write stub file: {e}")
        return 1
    
    print("\n" + "="*70)
    print("V - Successfully generated iode_cython.py from iode_cython.pyi")
    print("="*70)
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
