Version 7.0-beta.3
===================

In development

New Features 🎉
---------------


Improvements ✨
---------------

* (GUI) Allow to copy/paste variables values from/to Excel (#294)

Fixed Bugs 🛠️
-------------

* (GUI) Fixed windows representing Generalized Sample tables not being able to be displayed in fullscreen (#290)

* (GUI) Fixed IODE objects tabs not being updated when running any item from the menus of the main window (#295)

* (GUI) Fixed shortcut F7 (Shift + F7) to execute selected identity (identities) (#306)

* (GUI) Fixed shortcut F7 to compute and display the values of a table (#307)

* (GUI) Fixed shortcut F8 to compute and display the values of a table as a graph (#307)

* (GUI) Enabled the menu Print/Graphs > Graphs from Tables (#309)

Miscellaneous 🤷‍♀️
----------------

