Version 7.0-beta.3
===================

In development

New Features 🎉
---------------


Improvements ✨
---------------

* (GUI) Allow to copy/paste variables values from/to Excel (#294)

Fixed Bugs 🛠️
-------------

* (GUI) Fixed windows representing Generalized Sample tables not being able to be displayed in fullscreen (#290)

* (GUI) Fixed IODE objects tabs not being updated when running any item from the menus of the main window (#295)

Miscellaneous 🤷‍♀️
----------------

