Version 7.0-beta.4
==================

In development

New Features 🎉
---------------

  * (GUI) The tables and text editors in tabs can be splitted (#127)

Improvements ✨
---------------


Fixed Bugs 🛠️
-------------

  * (GUI) Opens .rtf files with Microsoft Word by default instead of displaying their content in a new text tab (#291)
  * (GUI) Pressing (SHIFT+)F5 when displaying the variables will move to the (previous) next mode 
          (level, difference, growth rate) (#320)

Miscellaneous 🤷‍♀️
----------------

