Version 7.01-beta.2
===================

Released on 12/07/2023.

Improvements ✨
---------------

* (GUI) Added `Open As Text` option to the context menu in the File Explorer (#268).

* (GUI) Reload the values for the report parameters, language and nb decimals for each report tab when relaunching the GUI (#274)

Fixed Bugs 🛠️
--------------

* (GUI) fixed multi-line edition of comments, equations LEC, identities, lists and table titles (#272)

* (GUI) fixed IODE database tabs not updated when calling $WsLoad<...> from an IODE report or using the IODE command line (#276).

* (GUI) fixed IODE database tabs not updated when calling $WsClear<...> from an IODE report or using the IODE command line (#277).

* (GUI) fixed double click on a IODE database file in the File Explorer not reloading it (#278).
