Version7.0-beta.6
=================

In development

New Features 🎉
---------------


Improvements ✨
---------------

  * (GUI) Align values right when displaying numbers (#445)


Fixed Bugs 🛠️
-------------

  * (GUI) Fixed tab 'Tests By Equation' not displaying tests values for all equations 
          when the block to estimate contains more than one equation (#443)
  * (GUI) Do not stretch the last column when displaying numeric values + do not stretch 
          the last row in any case (#446)


Miscellaneous 🤷‍♀️
----------------

