Version7.0-beta.5
=================

In development

New Features 🎉
---------------


Improvements ✨
---------------

  * (GUI) Enabled editing Comments, Identities and Lists in box dialogs (shortcut: CTRL + ENTER / RETURN) (#364) 


Fixed Bugs 🛠️
-------------

  * (GUI) Fixed table cells edition: if the content starts with a double quote, then it is of type string. 
          Otherwise, it is of type LEC (#363)
  * (GUI) Fixed combobox `Object type` not working when opening the box dialog from the menu 
          Workspace > Copy / Merge Into Workspace (#362)


Miscellaneous 🤷‍♀️
----------------

