Version7.0-beta.6
=================

In development

New Features 🎉
---------------


Improvements ✨
---------------

  * (GUI) Align values right when displaying numbers (#445)
  * (GUI) Possibility to choose between running reports from the project directory or 
          from their parent directory (#447)
  * (GUI) The graphical user interval remembers the last 20 executed commands when the 
          user reopens it (#386) 


Fixed Bugs 🛠️
-------------

  * (GUI) Fixed tab 'Tests By Equation' not displaying tests values for all equations 
          when the block to estimate contains more than one equation (#443)
  * (GUI) Do not stretch the last column when displaying numeric values + do not stretch 
          the last row in any case (#446)
  * (GUI) Fixed loss of precision when copying from IODE Variables and pasting to an Excel workbook 
          (values are copied with maximum precision possible) (#448)
  * (GUI) Fixed use the shortcut CTRL (+ ALT) + F1...F7 more than once (cascading) (#464)


Miscellaneous 🤷‍♀️
----------------

