	    SCR/AL1 : MULTI-LINGUAL MESSAGE FILE
	    ------------------------------------

 Syntax of each line :

    message number or name | message language 1 | message language 2 ...

 Note : - message numbers 0..999 are reserved for SCR/AL1 internal use
	- message numbers or names must begin in 1rst column and
	  are case sensitive
------------------------------------------------------------------------
 Messages de IODE
 ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

1256 | Save WS : filename too long
1001  | W S   S T A T U S
1002  | S A V E   W S
1003  | CHANGE WS NAMES AND DESCRIPTIONS
1004  | New sample invalid
1005  | Are you sure ? (Y/N)
1006  | Do you want to leave ODE ? (Y/N)
1007  | Replace existing (Y/N)
1008  | Stop simulation (Y/N)
1009  | Delete (Y/N) ?
1010 | Save first ? (Y/N)
1011 | Stop (Y/N)
1012 | Profile loaded
1013 | Profile saved
1014 | Program '%.80s' not found
1015 | No output file defined
1016 | Sample modified
1017 | Estimation Achieved
1018 | Execution of Identities achieved
1019 | Simulation Achieved
1020 | Objects Printed
1021 | Tables/Graphs printed
1022 | Tables Viewed
1023 | File deleted
1024 | File !%.30s:%.30s! error
1025 | File copied
1026 | File renamed
1027 | File printed
1028 | Illegal argument(s)
1029 | Delete %.50s failed
1030 | DataRename %.20s to %.20s failed
1031 | DataDuplicate of Equations has no sense
1032 | DataDuplicate %.20s to %.20s failed
1033 | DataUpdateScl : Invalid Argument
1034 | Update of tables : Use the fullscreen Editor
1035 | DataUpdateVar : '%.80s' Invalid Argument
1036 | Pattern '%.80s' unmatched
1037 | List '%.80s' cannot be set
1038 | No file found for mask %.80s
1039 | EqsEstimate: %.80s %.80s wrong sample
1040 | EqsEstimate: empty equation list
1041 | FileCopy: unable to open file %.80s
1042 | FileCopy: unable to create file %.80s
1043 | FileCopy: error writing %.80s
1044 | Cannot delete %.80s
1045 | FilePrint: unable open input file %.80s
1046 | FilePrint: error writing output file %.80s
1047 | Unable to rename %.80s
1048 | IdtExecute: %.80s %.80s wrong sample
1049 | ModelSimulate: %.80s %.80s wrong sample
1050 | Error printing object %.80s
1051 | Object %.80s not found
1052 | Cannot open '%.80s'
1053 | %.80s : invalid number of decimals (value = 2)
1054 | Table %.80s not found
1055 | Table %.80s not printed
1056 | Wrong sample definition
1057 | Cannot load profile %.80s
1058 | Cannot save profile %.80s
1059 | Table %.80s not viewed
1060 | '%.80s' : invalid ODE file
1061 | Unused error 61
1062 | Sample %.80s : syntax error
1063 | Unable to print line %d
1064 | DataDisplayGraph : '%.80s' undefined
1065 | List '%.80s' not in ws
1066 | Sorted List %.80s cannot be created
1067 | DataEditGraph : Syntax error
1068 | No variable defined
1069 | DataDisplayGraph : empty variable list
1070 | DataDisplayGraph : Sample out of WS bounds
1071 | Only dimension 2 tables can be graphed
1072 | Testing failed ...
1073 | Invalid Reference number
1074 | Invalid argument
1075 | Too many repetitions in generalized sample
1076 | Cannot create tmp file ws.rep
1077 | No scalars in your system
1078 | Error printing object '%.80s'
1079 | Object %.80s not found
1080 | Table %.80s not found
1081 | Table %.80s not printed
1082 | No tables defined
1083 | Invalid language
1084 | File 'readme.ode' not found
1085 | Different periodicities
1086 | %.80s : incorrect period
1087 | Sample out of WS bounds
1088 | Illegal sample : %.80s %.80s
1089 | Error in estimation period
1090 | Var %.80s not found
1091 | ... others skipped
1092 | Scl %.80s not found
1093 | Empty execution sample
1094 | Empty set of identities
1095 | Circular identity definition
1096 | VarFile '%.80s' not found
1097 | SclFile '%.80s' not found
1098 |  %.80s : not found
1099 |  %.80s : skipped (low memory)
1100 | C O M P U T E   A N D   D I S P L A Y   T A B L E S
1101 | C O M P U T E   A N D   D I S P L A Y   G R A P H I C S
1102 | D I S P L A Y   A N D   P R I N T   T A B L E S
1103 | D I S P L A Y   A N D   P R I N T   G R A P H I C S
1104 | E D I T   A   R E P O R T
1105 | E X E C U T E   A   R E P O R T
1110 | Empty set of equations
1111 | Simulation sample out of WS boundaries
1112 | %.80s : cannot find variable
1113 | %.80s : cannot link
1114 | Model does not converge after %d iterations
1115 | %.80s : syntax error in goal seeking parameter
1116 | Goal Seeking: %.80s - no such equation in WS
1117 | Goal Seeking: %.80s-%.80s no exchange possible
1118 | Goal Seeking: %.80s already exchanged
1119 | Goal Seeking: %.80s already endogeneous
1120 | Equation %.80s not found
1121 | Equation %.80s : estimation sample undefined
1130 | WsExtrapolate : syntax error (method from to vars ...)
1131 | WsExtrapolate : sample definition error
1132 | DataSearch : not found
1133 | DataList : not found
1134 | WsCopy : invalid argument(s)
1135 | WsCopy : object list required
1136 | WsAggr* : syntax error (pattern [filename])
1137 | DataStatVar : syntax error (order lec;lec;...)
1201 | Estimation : No equation
1202 | Estimation : Memory Error
1203 | Estimation : Syntax Error
1204 | Estimation : Link Error
1205 | Estimation : Dreg Error
1206 | Estimation : NaN Generated
1207 | Estimation : Singular Matrix (VCC)
1208 | Estimation : Singular Matrix (VCU)
1209 | Estimation : Singular Matrix (GMG)
1210 | Estimation : No current estimation
1211 | Estimation : Memory Full
1211 | Estimation : Equation %.80s : compiling error %.80s
1212 | Estimation : Instrument %.80s : error %.80s
1213 | Block: syntax error
1250 | Report : Memory Full
1251 | Report : Define of %.80s (%.80s) not possible
1252 | Report : Argument (%d) not there
1253 | Report : Macro %.80s undefined
1254 | Report : Argument definition (%.80s) to long
1255 | Report : Macro definition (%.80s) to long
1300 | RAS : Var %s not found
1301 | RAS : diverges (%f > %f)
1302 | RAS : sum of rows (%f) <> sum of cols (%f)
1303 | Invalid PrintMulti option (None, Stacked, Percent)
1304 | Invalid GraphDefault option (Line, Scatter, Bar)

 Messages utilis‚s fr‚quemment : 400 .. 999
 ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
401 |Rejected operation|Op‚ration rejet‚e|Verboden wijziging
500 |Alt+Q=Quit Alt+W=Save|Alt+Q=Quitter Alt+W=Sauver|Alt+Q=Verlaten Alt+W=Opslaan
501 |Press any key to continue|Pressez une touche pour continuer|Druk op een toets
502 |Yes|Oui|Ja
503 |No|Non|Neen
505 |Modify|Modifier|Wijzigen
506 |View|Consulter|Bekijken
507 |Create|Cr‚er|Aanmaken
508 |Delete|D‚truire|Vernietigen
509 |Quit|Quitter|Verlaten
File|File|Fichier|Bestand
510 |Related topics|Sujets connexes|Verwante begrippen
511 |Enter Y or N|Tapez O ou N|Druk op J of N
512 |Header|Entˆte|Header
513 |Mark|Marque|Mark
514 |Unmark|D‚marque|Unmark
515 |Copy|Copie|Copieren
516 |Delete|D‚truit|Vernietigen
517 |Help|Aide|Hulp

 Autres messages g‚n‚raux
 ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
0   |can't access file|accŠs au fichier impossible|bestand niet bereikbaar
1   |keyword unknown
2   |field unknown
6   |string expected
7   |integer expected
8   |different types
9   |field empty
10  |no name
11  |Isam field undefined
12  |Incorrect isam field
13  |syntax error|erreur de syntaxe|syntax fout
14  |memory full|m‚moire d‚pass‚e|geheugen probleem
15  |file not open
16  |no page defined
17  |no index
18  |incorrect condition
19  |undefined object
20  |string too long
21  |length error
22  |duplicate
23  |no action
24  |no option
25  |object empty
26  |unexpected EOF
27  |cannot lock record
28  |cannot unlock record
29  |name does not exist
30  |screen size > page size
31  |first isam field is numeric
32  |menu field expected
33  |natural or string field expected
34  |index of LBC must be NODUP
35  |VIEW : isam length error

100 |File !%s:%s! error|Fichier !%s:%s! : erreur|Bestand !%s:%s! : fout
101 |Record not found file %s|Enregistrement non trouv‚ dans le fichier %s|Gegeven niet gevonden in bestand %s
102 |Help file undefined|Fichier d'aide ind‚fini|Help bestand onbekend
103 |Cannot open '%s'|Impossible d'ouvrir le fichier %s|Bestand %s niet te openen
104 |Incorrect help format (file %s)|Fichier %s : format incorrect|Bestand %s : foutief formaat
105 |%d occurences replaced|%d occurences remplac‚es|%d keer vervangen
106 |"%s" not found|"%s" non trouv‚|"%s" niet gevonden
107 |Isam file modified (or corrupted)|Base de donn‚es modifi‚e (ou erronn‚e)|Data bestand gewijzigd (of foutief)
108 |Arguments of IS_open_files incorrect
109 |Can't access '%s' : %s|AccŠs … '%s' impossible : '%s'|'%s' niet bereikbaar : '%s'
110 |Arguments of IS_close_files incorrect
111 |Arguments of IS_open_files incorrect
112 |Can't open %s|Impossible d'ouvrir %s|%s niet te openen
113 |Permission denied
114 |No record selected|Pas d'enregistrement s‚lectionn‚|Geen geselecteerd gegevens
115 |Duplicate index|Double index|Dubbele index
116 |Character '%c' not in '%s'
117 |Confirm|Confirmation|Bevestig
150 |ENTER=Open TAB=Select F1=Contents F2=Previous ESC=Quit
