# Composite Action
# See https://docs.github.com/en/actions/creating-actions/creating-a-composite-action 
# and https://stackoverflow.com/a/75279262 

name: install_boost
description: 'Install C++ Boost library'
runs:
  using: 'composite'
  steps:
    - name: Install Boost
      uses: MarkusJx/install-boost@v2.4.1
      id: install-boost
      with:
        # REQUIRED: Specify the required boost version
        # A list of supported versions can be found here:
        # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
        boost_version: 1.80.0
        # OPTIONAL: Specify a custom install location
        boost_install_dir: C:\
        # OPTIONAL: Specify a platform version
        platform_version: 2019
        # OPTIONAL: Specify a toolset
        toolset: msvc
        # NOTE: If a boost version matching all requirements cannot be found,
        # this build step will fail
