# Composite Action
# See https://docs.github.com/en/actions/creating-actions/creating-a-composite-action 
# and https://stackoverflow.com/a/75279262 

name: build_api
description: 'Build SCR4 lib and the C and C++ API'
inputs:
  cmake-config:
    description: 'CMake build config'
    required: true
    default: 'windows-debug'
runs:
  using: 'composite'
  steps:
    - name: Build SCR4
      shell: bash
      # cmake --build --preset <buildPreset> where <buildPreset> is the name of the active Build Preset.
      # see CMakePresets.json file
      run: cmake --build --preset ${{ inputs.cmake-config }} --target iode_scr4 
    - name: Build C IODE API
      shell: bash
      run: cmake --build --preset ${{ inputs.cmake-config }} --target iode_c_api 
    - name: Build C++ IODE API
      shell: bash
      run: cmake --build --preset ${{ inputs.cmake-config }} --target iode_cpp_api 
