name: Build GUI executable

on: 
  # line below makes jobs defined in this script (workflow) reusable
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:
    inputs:
      build-config:
        default: 'windows-debug'
        required: true
        type: string

jobs:
    build_gui:
        name: Build Graphical User Interface
        strategy:
            matrix:
                os: [windows-latest]

        runs-on: ${{ matrix.os }}

        steps:
            - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
            - run: echo "This job is now running on a ${{ runner.os }} server"
            - run: echo "The name of the repository is ${{ github.repository }}."
            - run: echo "The target branch of the current pull request is ${{ github.base_ref }}."
            - run: echo "The source branch of the current pull request is ${{ github.head_ref }}."
            - run: echo "The workspace directory is ${{ github.workspace }}."
            - name: Checkout repository code
              uses: actions/checkout@v2
            - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
            - name: Install Qt
              uses: ./.github/actions/install_qt
            - name: Build the SCR4, C and C++ API libs
              uses: ./.github/actions/build_api
              with:
                cmake-config: ${{ inputs.build-config }}
            - name: Test the C and C++ APIs
              uses: ./.github/actions/test_api
              with:
                cmake-config: ${{ inputs.build-config }}
            - name: Build GUI
              run: cmake --build --preset ${{ inputs.build-config }} --target iode_gui
            - run: echo "This job's status is ${{ job.status }}."
